apiVersion: v1
kind: Pod
metadata:
  name: nginx
spec:
  containers:
  - name: frontend
    image: nginx
    ports:
    - containerPort: 80
  - name: backend
    image: node
    ports:
    - containerPort: 8080