---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-cm
data:
  URL: google.com
  DB_HOST: xyz.com
---
apiVersion: v1
kind: Secret
metadata:
  name: demo-secret
data:
  USERNAME: YWRtaW4=
  PASSWORD: QWRtaW4xMjM=
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-07
spec:
  containers:
    - name: test
      image: docker.io/rkalluru/centos-sleep
      env:
        - name: URL
          valueFrom:
            configMapKeyRef:
              name: demo-cm
              key: URL
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: demo-secret
              key: USERNAME

